spring.application.name=gym-crm-spring-boot
logging.pattern.level=%5p [transactionId=%X{transactionId}]

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always